[options]
girs_dir = "gir-files"
library = "GUdev"
version = "1.0"
min_cfg_version = "230"
target_path = "."
work_mode = "normal"

generate = [
    "GUdev.Client",
    "GUdev.Device",
    "GUdev.DeviceType",
]

ignore = [
]

manual = [

]
