// Generated by gir (https://github.com/gtk-rs/gir @ e0d8d8d645b1)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 3ff4d3275258)
// from gudev-gir
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GUdevClient", sizeof(GUdevClient), alignof(GUdevClient));
    printf("%s;%zu;%zu\n", "GUdevClientClass", sizeof(GUdevClientClass), alignof(GUdevClientClass));
    printf("%s;%zu;%zu\n", "GUdevDevice", sizeof(GUdevDevice), alignof(GUdevDevice));
    printf("%s;%zu;%zu\n", "GUdevDeviceClass", sizeof(GUdevDeviceClass), alignof(GUdevDeviceClass));
    printf("%s;%zu;%zu\n", "GUdevDeviceNumber", sizeof(GUdevDeviceNumber), alignof(GUdevDeviceNumber));
    printf("%s;%zu;%zu\n", "GUdevDeviceType", sizeof(GUdevDeviceType), alignof(GUdevDeviceType));
    printf("%s;%zu;%zu\n", "GUdevEnumerator", sizeof(GUdevEnumerator), alignof(GUdevEnumerator));
    printf("%s;%zu;%zu\n", "GUdevEnumeratorClass", sizeof(GUdevEnumeratorClass), alignof(GUdevEnumeratorClass));
    return 0;
}
