// This file was generated by gir (https://github.com/gtk-rs/gir @ 907cd81)
// from gir-files (https://github.com/gtk-rs/gir-files @ be1cc90)
// DO NOT EDIT

use crate::DeviceNumber;
use crate::DeviceType;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct Device(Object<ffi::GUdevDevice, ffi::GUdevDeviceClass>);

    match fn {
        get_type => || ffi::g_udev_device_get_type(),
    }
}

pub const NONE_DEVICE: Option<&Device> = None;

pub trait DeviceExt: 'static {
    #[doc(alias = "g_udev_device_get_action")]
    fn get_action(&self) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_device_file")]
    fn get_device_file(&self) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_device_file_symlinks")]
    fn get_device_file_symlinks(&self) -> Vec<glib::GString>;

    #[doc(alias = "g_udev_device_get_device_number")]
    fn get_device_number(&self) -> DeviceNumber;

    #[doc(alias = "g_udev_device_get_device_type")]
    fn get_device_type(&self) -> DeviceType;

    #[doc(alias = "g_udev_device_get_devtype")]
    fn get_devtype(&self) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_driver")]
    fn get_driver(&self) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_is_initialized")]
    fn get_is_initialized(&self) -> bool;

    #[doc(alias = "g_udev_device_get_name")]
    fn get_name(&self) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_number")]
    fn get_number(&self) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_parent")]
    fn get_parent(&self) -> Option<Device>;

    #[doc(alias = "g_udev_device_get_parent_with_subsystem")]
    fn get_parent_with_subsystem(&self, subsystem: &str, devtype: Option<&str>) -> Option<Device>;

    #[doc(alias = "g_udev_device_get_property")]
    fn get_property(&self, key: &str) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_property_as_boolean")]
    fn get_property_as_boolean(&self, key: &str) -> bool;

    #[doc(alias = "g_udev_device_get_property_as_double")]
    fn get_property_as_double(&self, key: &str) -> f64;

    #[doc(alias = "g_udev_device_get_property_as_int")]
    fn get_property_as_int(&self, key: &str) -> i32;

    #[doc(alias = "g_udev_device_get_property_as_strv")]
    fn get_property_as_strv(&self, key: &str) -> Vec<glib::GString>;

    #[doc(alias = "g_udev_device_get_property_as_uint64")]
    fn get_property_as_uint64(&self, key: &str) -> u64;

    #[doc(alias = "g_udev_device_get_property_keys")]
    fn get_property_keys(&self) -> Vec<glib::GString>;

    #[doc(alias = "g_udev_device_get_seqnum")]
    fn get_seqnum(&self) -> u64;

    #[doc(alias = "g_udev_device_get_subsystem")]
    fn get_subsystem(&self) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_sysfs_attr")]
    fn get_sysfs_attr(&self, name: &str) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_sysfs_attr_as_boolean")]
    fn get_sysfs_attr_as_boolean(&self, name: &str) -> bool;

    #[doc(alias = "g_udev_device_get_sysfs_attr_as_double")]
    fn get_sysfs_attr_as_double(&self, name: &str) -> f64;

    #[doc(alias = "g_udev_device_get_sysfs_attr_as_int")]
    fn get_sysfs_attr_as_int(&self, name: &str) -> i32;

    #[doc(alias = "g_udev_device_get_sysfs_attr_as_strv")]
    fn get_sysfs_attr_as_strv(&self, name: &str) -> Vec<glib::GString>;

    #[doc(alias = "g_udev_device_get_sysfs_attr_as_uint64")]
    fn get_sysfs_attr_as_uint64(&self, name: &str) -> u64;

    #[doc(alias = "g_udev_device_get_sysfs_attr_keys")]
    fn get_sysfs_attr_keys(&self) -> Vec<glib::GString>;

    #[doc(alias = "g_udev_device_get_sysfs_path")]
    fn get_sysfs_path(&self) -> Option<glib::GString>;

    #[doc(alias = "g_udev_device_get_tags")]
    fn get_tags(&self) -> Vec<glib::GString>;

    #[doc(alias = "g_udev_device_get_usec_since_initialized")]
    fn get_usec_since_initialized(&self) -> u64;

    #[doc(alias = "g_udev_device_has_property")]
    fn has_property(&self, key: &str) -> bool;

    #[doc(alias = "g_udev_device_has_sysfs_attr")]
    fn has_sysfs_attr(&self, key: &str) -> bool;
}

impl<O: IsA<Device>> DeviceExt for O {
    fn get_action(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_action(self.as_ref().to_glib_none().0))
        }
    }

    fn get_device_file(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_device_file(self.as_ref().to_glib_none().0))
        }
    }

    fn get_device_file_symlinks(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_device_file_symlinks(self.as_ref().to_glib_none().0))
        }
    }

    fn get_device_number(&self) -> DeviceNumber {
        unsafe {
            ffi::g_udev_device_get_device_number(self.as_ref().to_glib_none().0)
        }
    }

    fn get_device_type(&self) -> DeviceType {
        unsafe {
            from_glib(ffi::g_udev_device_get_device_type(self.as_ref().to_glib_none().0))
        }
    }

    fn get_devtype(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_devtype(self.as_ref().to_glib_none().0))
        }
    }

    fn get_driver(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_driver(self.as_ref().to_glib_none().0))
        }
    }

    fn get_is_initialized(&self) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_get_is_initialized(self.as_ref().to_glib_none().0))
        }
    }

    fn get_name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_name(self.as_ref().to_glib_none().0))
        }
    }

    fn get_number(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_number(self.as_ref().to_glib_none().0))
        }
    }

    fn get_parent(&self) -> Option<Device> {
        unsafe {
            from_glib_full(ffi::g_udev_device_get_parent(self.as_ref().to_glib_none().0))
        }
    }

    fn get_parent_with_subsystem(&self, subsystem: &str, devtype: Option<&str>) -> Option<Device> {
        unsafe {
            from_glib_full(ffi::g_udev_device_get_parent_with_subsystem(self.as_ref().to_glib_none().0, subsystem.to_glib_none().0, devtype.to_glib_none().0))
        }
    }

    fn get_property(&self, key: &str) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_property(self.as_ref().to_glib_none().0, key.to_glib_none().0))
        }
    }

    fn get_property_as_boolean(&self, key: &str) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_get_property_as_boolean(self.as_ref().to_glib_none().0, key.to_glib_none().0))
        }
    }

    fn get_property_as_double(&self, key: &str) -> f64 {
        unsafe {
            ffi::g_udev_device_get_property_as_double(self.as_ref().to_glib_none().0, key.to_glib_none().0)
        }
    }

    fn get_property_as_int(&self, key: &str) -> i32 {
        unsafe {
            ffi::g_udev_device_get_property_as_int(self.as_ref().to_glib_none().0, key.to_glib_none().0)
        }
    }

    fn get_property_as_strv(&self, key: &str) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_property_as_strv(self.as_ref().to_glib_none().0, key.to_glib_none().0))
        }
    }

    fn get_property_as_uint64(&self, key: &str) -> u64 {
        unsafe {
            ffi::g_udev_device_get_property_as_uint64(self.as_ref().to_glib_none().0, key.to_glib_none().0)
        }
    }

    fn get_property_keys(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_property_keys(self.as_ref().to_glib_none().0))
        }
    }

    fn get_seqnum(&self) -> u64 {
        unsafe {
            ffi::g_udev_device_get_seqnum(self.as_ref().to_glib_none().0)
        }
    }

    fn get_subsystem(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_subsystem(self.as_ref().to_glib_none().0))
        }
    }

    fn get_sysfs_attr(&self, name: &str) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_sysfs_attr(self.as_ref().to_glib_none().0, name.to_glib_none().0))
        }
    }

    fn get_sysfs_attr_as_boolean(&self, name: &str) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_get_sysfs_attr_as_boolean(self.as_ref().to_glib_none().0, name.to_glib_none().0))
        }
    }

    fn get_sysfs_attr_as_double(&self, name: &str) -> f64 {
        unsafe {
            ffi::g_udev_device_get_sysfs_attr_as_double(self.as_ref().to_glib_none().0, name.to_glib_none().0)
        }
    }

    fn get_sysfs_attr_as_int(&self, name: &str) -> i32 {
        unsafe {
            ffi::g_udev_device_get_sysfs_attr_as_int(self.as_ref().to_glib_none().0, name.to_glib_none().0)
        }
    }

    fn get_sysfs_attr_as_strv(&self, name: &str) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_sysfs_attr_as_strv(self.as_ref().to_glib_none().0, name.to_glib_none().0))
        }
    }

    fn get_sysfs_attr_as_uint64(&self, name: &str) -> u64 {
        unsafe {
            ffi::g_udev_device_get_sysfs_attr_as_uint64(self.as_ref().to_glib_none().0, name.to_glib_none().0)
        }
    }

    fn get_sysfs_attr_keys(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_sysfs_attr_keys(self.as_ref().to_glib_none().0))
        }
    }

    fn get_sysfs_path(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_sysfs_path(self.as_ref().to_glib_none().0))
        }
    }

    fn get_tags(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_tags(self.as_ref().to_glib_none().0))
        }
    }

    fn get_usec_since_initialized(&self) -> u64 {
        unsafe {
            ffi::g_udev_device_get_usec_since_initialized(self.as_ref().to_glib_none().0)
        }
    }

    fn has_property(&self, key: &str) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_has_property(self.as_ref().to_glib_none().0, key.to_glib_none().0))
        }
    }

    fn has_sysfs_attr(&self, key: &str) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_has_sysfs_attr(self.as_ref().to_glib_none().0, key.to_glib_none().0))
        }
    }
}

impl fmt::Display for Device {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Device")
    }
}
