// This file was generated by gir (9bd51ed) from gir-files (25c8aaf)
// DO NOT EDIT

use DeviceNumber;
use DeviceType;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct Device(Object<ffi::GUdevDevice>);

    match fn {
        get_type => || ffi::g_udev_device_get_type(),
    }
}

pub trait DeviceExt {
    fn get_action(&self) -> Option<String>;

    fn get_device_file(&self) -> Option<String>;

    fn get_device_file_symlinks(&self) -> Vec<String>;

    fn get_device_number(&self) -> DeviceNumber;

    fn get_device_type(&self) -> DeviceType;

    fn get_devtype(&self) -> Option<String>;

    fn get_driver(&self) -> Option<String>;

    fn get_is_initialized(&self) -> bool;

    fn get_name(&self) -> Option<String>;

    fn get_number(&self) -> Option<String>;

    fn get_parent(&self) -> Option<Device>;

    fn get_parent_with_subsystem<'a, P: Into<Option<&'a str>>>(&self, subsystem: &str, devtype: P) -> Option<Device>;

    fn get_property(&self, key: &str) -> Option<String>;

    fn get_property_as_boolean(&self, key: &str) -> bool;

    fn get_property_as_double(&self, key: &str) -> f64;

    fn get_property_as_int(&self, key: &str) -> i32;

    fn get_property_as_strv(&self, key: &str) -> Vec<String>;

    fn get_property_as_uint64(&self, key: &str) -> u64;

    fn get_property_keys(&self) -> Vec<String>;

    fn get_seqnum(&self) -> u64;

    fn get_subsystem(&self) -> Option<String>;

    fn get_sysfs_attr(&self, name: &str) -> Option<String>;

    fn get_sysfs_attr_as_boolean(&self, name: &str) -> bool;

    fn get_sysfs_attr_as_double(&self, name: &str) -> f64;

    fn get_sysfs_attr_as_int(&self, name: &str) -> i32;

    fn get_sysfs_attr_as_strv(&self, name: &str) -> Vec<String>;

    fn get_sysfs_attr_as_uint64(&self, name: &str) -> u64;

    fn get_sysfs_attr_keys(&self) -> Vec<String>;

    fn get_sysfs_path(&self) -> Option<String>;

    fn get_tags(&self) -> Vec<String>;

    fn get_usec_since_initialized(&self) -> u64;

    fn has_property(&self, key: &str) -> bool;

    fn has_sysfs_attr(&self, key: &str) -> bool;
}

impl<O: IsA<Device>> DeviceExt for O {
    fn get_action(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_action(self.to_glib_none().0))
        }
    }

    fn get_device_file(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_device_file(self.to_glib_none().0))
        }
    }

    fn get_device_file_symlinks(&self) -> Vec<String> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_device_file_symlinks(self.to_glib_none().0))
        }
    }

    fn get_device_number(&self) -> DeviceNumber {
        unsafe {
            ffi::g_udev_device_get_device_number(self.to_glib_none().0)
        }
    }

    fn get_device_type(&self) -> DeviceType {
        unsafe {
            from_glib(ffi::g_udev_device_get_device_type(self.to_glib_none().0))
        }
    }

    fn get_devtype(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_devtype(self.to_glib_none().0))
        }
    }

    fn get_driver(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_driver(self.to_glib_none().0))
        }
    }

    fn get_is_initialized(&self) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_get_is_initialized(self.to_glib_none().0))
        }
    }

    fn get_name(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_name(self.to_glib_none().0))
        }
    }

    fn get_number(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_number(self.to_glib_none().0))
        }
    }

    fn get_parent(&self) -> Option<Device> {
        unsafe {
            from_glib_full(ffi::g_udev_device_get_parent(self.to_glib_none().0))
        }
    }

    fn get_parent_with_subsystem<'a, P: Into<Option<&'a str>>>(&self, subsystem: &str, devtype: P) -> Option<Device> {
        let devtype = devtype.into();
        let devtype = devtype.to_glib_none();
        unsafe {
            from_glib_full(ffi::g_udev_device_get_parent_with_subsystem(self.to_glib_none().0, subsystem.to_glib_none().0, devtype.0))
        }
    }

    fn get_property(&self, key: &str) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_property(self.to_glib_none().0, key.to_glib_none().0))
        }
    }

    fn get_property_as_boolean(&self, key: &str) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_get_property_as_boolean(self.to_glib_none().0, key.to_glib_none().0))
        }
    }

    fn get_property_as_double(&self, key: &str) -> f64 {
        unsafe {
            ffi::g_udev_device_get_property_as_double(self.to_glib_none().0, key.to_glib_none().0)
        }
    }

    fn get_property_as_int(&self, key: &str) -> i32 {
        unsafe {
            ffi::g_udev_device_get_property_as_int(self.to_glib_none().0, key.to_glib_none().0)
        }
    }

    fn get_property_as_strv(&self, key: &str) -> Vec<String> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_property_as_strv(self.to_glib_none().0, key.to_glib_none().0))
        }
    }

    fn get_property_as_uint64(&self, key: &str) -> u64 {
        unsafe {
            ffi::g_udev_device_get_property_as_uint64(self.to_glib_none().0, key.to_glib_none().0)
        }
    }

    fn get_property_keys(&self) -> Vec<String> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_property_keys(self.to_glib_none().0))
        }
    }

    fn get_seqnum(&self) -> u64 {
        unsafe {
            ffi::g_udev_device_get_seqnum(self.to_glib_none().0)
        }
    }

    fn get_subsystem(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_subsystem(self.to_glib_none().0))
        }
    }

    fn get_sysfs_attr(&self, name: &str) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_sysfs_attr(self.to_glib_none().0, name.to_glib_none().0))
        }
    }

    fn get_sysfs_attr_as_boolean(&self, name: &str) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_get_sysfs_attr_as_boolean(self.to_glib_none().0, name.to_glib_none().0))
        }
    }

    fn get_sysfs_attr_as_double(&self, name: &str) -> f64 {
        unsafe {
            ffi::g_udev_device_get_sysfs_attr_as_double(self.to_glib_none().0, name.to_glib_none().0)
        }
    }

    fn get_sysfs_attr_as_int(&self, name: &str) -> i32 {
        unsafe {
            ffi::g_udev_device_get_sysfs_attr_as_int(self.to_glib_none().0, name.to_glib_none().0)
        }
    }

    fn get_sysfs_attr_as_strv(&self, name: &str) -> Vec<String> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_sysfs_attr_as_strv(self.to_glib_none().0, name.to_glib_none().0))
        }
    }

    fn get_sysfs_attr_as_uint64(&self, name: &str) -> u64 {
        unsafe {
            ffi::g_udev_device_get_sysfs_attr_as_uint64(self.to_glib_none().0, name.to_glib_none().0)
        }
    }

    fn get_sysfs_attr_keys(&self) -> Vec<String> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_sysfs_attr_keys(self.to_glib_none().0))
        }
    }

    fn get_sysfs_path(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::g_udev_device_get_sysfs_path(self.to_glib_none().0))
        }
    }

    fn get_tags(&self) -> Vec<String> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::g_udev_device_get_tags(self.to_glib_none().0))
        }
    }

    fn get_usec_since_initialized(&self) -> u64 {
        unsafe {
            ffi::g_udev_device_get_usec_since_initialized(self.to_glib_none().0)
        }
    }

    fn has_property(&self, key: &str) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_has_property(self.to_glib_none().0, key.to_glib_none().0))
        }
    }

    fn has_sysfs_attr(&self, key: &str) -> bool {
        unsafe {
            from_glib(ffi::g_udev_device_has_sysfs_attr(self.to_glib_none().0, key.to_glib_none().0))
        }
    }
}
