// This file was generated by gir (https://github.com/gtk-rs/gir @ 5836573)
// from gir-files (https://github.com/gtk-rs/gir-files @ 25c8aaf)
// DO NOT EDIT

use glib::translate::*;
use glib::value::FromValue;
use glib::value::FromValueOptional;
use glib::value::SetValue;
use glib::value::Value;
use glib::StaticType;
use glib::Type;
use gobject_sys;
use gudev_sys;
use std::fmt;

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
pub enum DeviceType {
    None,
    Block,
    Char,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for DeviceType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "DeviceType::{}", match *self {
            DeviceType::None => "None",
            DeviceType::Block => "Block",
            DeviceType::Char => "Char",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for DeviceType {
    type GlibType = gudev_sys::GUdevDeviceType;

    fn to_glib(&self) -> gudev_sys::GUdevDeviceType {
        match *self {
            DeviceType::None => gudev_sys::G_UDEV_DEVICE_TYPE_NONE,
            DeviceType::Block => gudev_sys::G_UDEV_DEVICE_TYPE_BLOCK,
            DeviceType::Char => gudev_sys::G_UDEV_DEVICE_TYPE_CHAR,
            DeviceType::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<gudev_sys::GUdevDeviceType> for DeviceType {
    fn from_glib(value: gudev_sys::GUdevDeviceType) -> Self {
        match value {
            0 => DeviceType::None,
            98 => DeviceType::Block,
            99 => DeviceType::Char,
            value => DeviceType::__Unknown(value),
        }
    }
}

impl StaticType for DeviceType {
    fn static_type() -> Type {
        unsafe { from_glib(gudev_sys::g_udev_device_type_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for DeviceType {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for DeviceType {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for DeviceType {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

