
[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.4"
glib-sys = "^0"
gobject-sys = "^0"
libc = "0.2"

[features]

[package]
authors = ["Hubert Figuière <hub@figuiere.net>"]
build = "build.rs"
links = "gudev"
name = "gudev-sys"
version = "0.1.0"
