
[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.4"
glib-sys = { git="https://github.com/gtk-rs/sys" }
gobject-sys = { git="https://github.com/gtk-rs/sys" }
libc = "0.2"

[features]

[lib]
name = "gudev_sys"

[package]
authors = ["Hubert Figuière <hub@figuiere.net>"]
build = "build.rs"
links = "gudev"
name = "gudev-sys"
version = "0.1.0"
