// Generated by gir (https://github.com/gtk-rs/gir @ d1b319f6d8fb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ c23f21f51d54)
// from gudev-gir
// DO NOT EDIT

mod client;
pub use self::client::Client;

mod device;
pub use self::device::Device;

mod enumerator;
pub use self::enumerator::Enumerator;

mod enums;
pub use self::enums::DeviceType;

#[doc(hidden)]
pub mod traits {
    pub use super::client::ClientExt;
    pub use super::device::DeviceExt;
    pub use super::enumerator::EnumeratorExt;
}
