// Generated by gir (https://github.com/gtk-rs/gir @ 0e476ab5c1de)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git @ cfc0305f903b)
// DO NOT EDIT

mod client;
pub use self::client::Client;

mod device;
pub use self::device::Device;

mod enumerator;
pub use self::enumerator::Enumerator;

mod enums;
pub use self::enums::DeviceType;

pub(crate) mod traits {
    pub use super::client::ClientExt;
    pub use super::device::DeviceExt;
    pub use super::enumerator::EnumeratorExt;
}
