// Generated by gir (https://github.com/gtk-rs/gir @ 43b9242f6689)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 3ff4d3275258)
// DO NOT EDIT

mod client;
pub use self::client::Client;

mod device;
pub use self::device::Device;

mod enumerator;
pub use self::enumerator::Enumerator;

mod enums;
pub use self::enums::DeviceType;

#[doc(hidden)]
pub mod traits {
    pub use super::client::ClientExt;
    pub use super::device::DeviceExt;
    pub use super::enumerator::EnumeratorExt;
}
