[options]
girs_directories = [
    "../gir-files"
]
library = "GUdev"
version = "1.0"
min_cfg_version = "230"
target_path = "."
work_mode = "normal"

generate = [
    "GUdev.Device",
    "GUdev.DeviceType",
]

ignore = [
]

manual = [
    "GUdev.DeviceNumber"
]

[[object]]
name = "GUdev.Client"
status = "generate"
generate_builder = false

[[object]]
name = "GUdev.Enumerator"
status = "generate"
generate_builder = false