// Generated by gir (https://github.com/gtk-rs/gir @ d1b319f6d8fb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ c23f21f51d54)
// from gudev-gir
// DO NOT EDIT

#[cfg(not(feature = "dox"))]
use std::process;

#[cfg(feature = "dox")]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(feature = "dox"))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        process::exit(1);
    }
}
