
on:
  push:
    branches:
      - master
      - 0.16.x
  pull_request:

name: CI

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libgudev-1.0-dev -y 
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt,clippy
      - uses: actions-rs/cargo@v1
        name: Check
        with:
          command: check
      - uses: actions-rs/cargo@v1
        name: Test Suite
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: Rustfmt
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -- -D warnings
